ticket:10272: the clang workaround was only *mostly* harmless. Disable it under Windows.    Fix: typeinfo(82): error C2874: using-declaration causes a multiple declaration of 'type_info'
git-svn-id: http://source.icu-project.org/repos/icu/icu/trunk@35375 251d0590-4201-4cf1-90de-194747b24ca1